# -*- coding: utf-8 -*-
"""bot

Automatically generated by Colaboratory.

Original file is located at
    
"""

import tweepy
import time
import os
import numpy as np
import subprocess
import json
import os
from os.path import join, dirname
from dotenv import load_dotenv


CONFIG = {
    "AK":"",
    "AKS":"",
    "AT":"",
    "ATS":"",
}

AK = CONFIG["AK"]
AKS = CONFIG["AKS"]
AT = CONFIG["AT"]
ATS = CONFIG["ATS"]

auth = tweepy.OAuthHandler(AK,AKS)

auth.set_access_token(AT,ATS)

api = tweepy.API(auth)


def run():
    TWEET = text_gene()
    api.update_status(TWEET)
    return ("「{}」。投稿したお。".format(TWEET))

run()
